/**
 * policy.js - Policy Recommendations Page
 */
window.PolicyPage = {
  async render() {
    const main = Utils.clearMain();
    main.appendChild(Utils.el("h1", { className: "page-title" }, "Policy Recommendations"));
    main.appendChild(Utils.el("p", { className: "page-subtitle" }, "Deterministic rule-based interventions generated by the Policy Engine."));

    const filterBar = Utils.el("div", { className: "filter-bar" });
    const prioritySelect = Utils.el("select", { className: "filter-select", id: "policy-priority-filter" },
      Utils.el("option", { value: "" }, "All Priorities"),
      Utils.el("option", { value: "HIGH" }, "HIGH"),
      Utils.el("option", { value: "MEDIUM" }, "MEDIUM"),
      Utils.el("option", { value: "LOW" }, "LOW")
    );
    prioritySelect.addEventListener("change", () => this.reload());
    filterBar.appendChild(Utils.el("label", null, "Priority:"));
    filterBar.appendChild(prioritySelect);
    main.appendChild(filterBar);

    const content = Utils.el("div", { id: "policy-content" });
    main.appendChild(content);
    this.reload();
  },

  async reload() {
    const content = Utils.$("#policy-content");
    if (!content) return;
    content.innerHTML = "";
    content.appendChild(Utils.loadingState());

    const prioritySelect = Utils.$("#policy-priority-filter");
    const params = { limit: 200 };
    if (prioritySelect && prioritySelect.value) params.priority_level = prioritySelect.value;

    try {
      const res = await API.getPolicyRecommendations(params);
      const data = res.data || [];
      content.innerHTML = "";

      if (data.length === 0) { content.appendChild(Utils.emptyState("No policy recommendations available.")); return; }

      // Stats
      const high = data.filter(d => d.priority_level === "HIGH").length;
      const medium = data.filter(d => d.priority_level === "MEDIUM").length;
      const low = data.filter(d => d.priority_level === "LOW").length;
      const stats = Utils.el("div", { className: "grid-stats" });
      stats.appendChild(statCard("HIGH Priority", high, "Urgent interventions", "var(--color-critical)"));
      stats.appendChild(statCard("MEDIUM Priority", medium, "Planned interventions", "var(--color-moderate)"));
      stats.appendChild(statCard("LOW Priority", low, "Advisory interventions", "var(--color-supply)"));
      stats.appendChild(statCard("Total Recommendations", data.length, "Generated by rules engine"));
      content.appendChild(stats);

      // Table
      const tableCard = Utils.el("div", { className: "card grid-full" });
      tableCard.appendChild(Utils.el("div", { className: "card__header" }, "Intervention Details"));
      const tableBody = Utils.el("div", { className: "card__body", style: { overflowX: "auto" } });
      tableBody.appendChild(buildTable(
        ["Rule", "Priority", "State", "Sector", "Occupation", "Skill", "Intervention", "Capacity", "Cost"],
        data.map(d => [
          d.trigger_rule_id,
          Utils.priorityBadge(d.priority_level),
          d.target_state || "—",
          d.target_sector || "—",
          d.target_occupation || "—",
          d.target_skill || "—",
          d.recommended_intervention,
          Utils.fmtNum(d.estimated_capacity_needed),
          d.cost_impact_estimate || "—"
        ])
      ));
      tableCard.appendChild(tableBody);
      content.appendChild(tableCard);
    } catch (err) {
      content.innerHTML = "";
      content.appendChild(Utils.errorState(err.message));
    }
  }
};
